kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPOSITORY
      tags: latest
    when:
      branch: master