version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  front:
    docker:
      - image: circleci/node

jobs:
  front-install-dependencies:
    executor: front
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-packaging-front-dependencies-{{ checksum "package-lock.json" }}
            - v1-packaging-front-dependencies-
      - run:
          name: install-dependencies
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules
          key: v1-packaging-front-dependencies-{{ checksum "package-lock.json" }}
  front-qc-prettier:
    executor: front
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-packaging-front-dependencies-{{ checksum "package-lock.json" }}
            - v1-packaging-front-dependencies-
      - run:
          name: qc-prettier
          command: npm run prettier:check
  front-build:
    executor: front
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-packaging-front-dependencies-{{ checksum "package-lock.json" }}
            - v1-packaging-front-dependencies-
      - run:
          name: build
          command: npm run build
  front-unit-test:
    executor: front
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-packaging-front-dependencies-{{ checksum "package-lock.json" }}
            - v1-packaging-front-dependencies-
      - run:
          name: unit-test
          command: npm run test:unit

workflows:
  qc-test-deploy:
    jobs:
      - front-install-dependencies
      - front-qc-prettier:
          requires:
            - front-install-dependencies
      - front-build:
          requires:
            - front-install-dependencies
      - front-unit-test:
          requires:
            - front-install-dependencies
      - cypress/install:
          cache-key: >-
            v1-packaging-front-dependencies-cypress-{{ checksum "package-lock.json" }}
      - cypress/run:
          name: chrome-cypress-run
          requires:
            - cypress/install
          cache-key: >-
            v1-packaging-front-dependencies-cypress-{{ checksum "package-lock.json" }}
          start: npm start
          wait-on: "http://localhost:1234"
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          parallel: true
          parallelism: 2
      - cypress/run:
          name: firefox-cypress-run
          requires:
            - cypress/install
          cache-key: >-
            v1-packaging-front-dependencies-cypress-{{ checksum "package-lock.json" }}
          start: npm start
          wait-on: "http://localhost:1234"
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          parallel: true
          parallelism: 2
